version: '3'
services:

  php:
    build: './php/'
    container_name: myapp_php
    volumes:
      - ../server:/var/www/myapp
    expose:
      - 9000

  react:
    image: node:12.9-alpine
    container_name: myapp_react
    working_dir: "/var/www/html/react"
    command: /bin/sh -c "npm install && npm start"
    volumes:
      - "../react:/var/www/html/react"
    ports:
      - 3042:3000
    environment:
      - NODE_ENV=development
    depends_on:
      - server

  server:
    image: nginx:1.17-alpine
    container_name: myapp_server
    command: [nginx, '-g', 'daemon off;']
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../server:/var/www/myapp
    ports:
      - 8042:80
    depends_on:
      - php
      - database

  database:
    image: mysql:5.7
    container_name: myapp_database
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
    environment:
      - MYSQL_DATABASE=myappdb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - 3342:3306
